CREATE TABLE IF NOT EXISTS account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(60) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    nickname VARCHAR(16) NOT NULL,
    bio VARCHAR(255),
    status VARCHAR(255) NOT NULL
);

INSERT INTO account (email, encoded_password, nickname, bio, status) VALUES
('efub@example.com', 'testpw', 'efub', 'This is a bio', 'ACTIVE');
